### ISSUE TITLE
p2p code review

### ISSUE THREAD

**Issue by Kyle-Law** [Kyle-Law/tictactoe-ruby#7]

**Comment by nyatindopatrick** [comment]
Good work! Looks great👍

**Comment by patriciachrysy** [comment]
Good job @Kyle-Law !!! I like the big "Tic Tac Toe" displayed when the game starts. The code is clean but the classes are not doing all they are supposed to. Most of the job is pushed to the main and that makes the main look long and a bit messy. Also, there is not enough abstraction for your attribute, most of them have the att_accessor meaning they can be read and written just by accessing through the instance and that gives no control. You can create a module in your project in order to keep your main DRY. Apart from these optional remarks, your project looks great!!! 
Good job!!

**Comment by dili021** [comment]
Looking good! Nice win_check!
